name: YAYA Sample
on:
  workflow_dispatch:
jobs:
  toot:
    runs-on: windows-latest
    timeout-minutes: 5
    env:
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      PYTHONUTF8: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: pip install
        run: pip install -r requirements.txt
      - name: Sample
        run: python sample.py yaya
